In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import re
from IPython.display import display
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
!pip install xlrd>=2.0.1

#Очистка данных
1-ый файл

In [10]:
df = pd.read_excel(
    r'C:\Users\ktzhadmin\Desktop\Capstone project\Capstone_project_Data\nominal_income.xls',
    skiprows=10
)
df.head(3)

,Регион,2000,2001,2002,2003,2004,2005,2006,2007,2008,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,РЕСПУБЛИКА КАЗАХСТАН,6 352,7 670,8 958,10 533,12 817,15 787,19 152,25 226,32 984,...,67 321,76 575,83 710,93 135,104 282,116 126,130 616,164 438,189 953,215 979
1,АКМОЛИНСКАЯ ОБЛАСТЬ,4 817,5 656,6 765,7 976,9 441,11 443,14 945,20 053,26 292,...,56 579,65 213,72 866,80 809,91 933,107 224,122 039,151 345,168 301,187 922
2,АКТЮБИНСКАЯ ОБЛАСТЬ,6 916,8 264,9 752,11 351,13 750,16 982,19 347,24 702,35 010,...,60 921,65 913,74 092,80 967,92 696,98 360,115 009,142 531,163 509,191 514

In [11]:
df = df.fillna(0)

In [12]:
# 1. Составим список колонок годов (числа)
years = [col for col in df.columns if col != 'Регион']

# 2. Melt: превращаем таблицу "широкую" в "длинную"
df = df.melt(id_vars=['Регион'], value_vars=years,
                  var_name='Год', value_name='Nom_Income')

# 3. Приведем 'Год' к int (на всякий случай)
df['Год'] = df['Год'].astype(int)

print(df.head())

                    Регион   Год Nom_Income
0     РЕСПУБЛИКА КАЗАХСТАН  2000      6 352
1      АКМОЛИНСКАЯ ОБЛАСТЬ  2000      4 817
2      АКТЮБИНСКАЯ ОБЛАСТЬ  2000      6 916
3      АЛМАТИНСКАЯ ОБЛАСТЬ  2000      3 712
4       АТЫРАУСКАЯ ОБЛАСТЬ  2000     15 056

In [13]:
df['Nom_Income'] = df['Nom_Income'].astype(str).str.replace(' ', '')
df['Nom_Income'] = df['Nom_Income'].astype(float)

In [14]:
df['Регион'] = df['Регион'].astype(str).str.replace('    ', '')

In [15]:
regions_needed = ['АЛМАТИНСКАЯ ОБЛАСТЬ', 'ОБЛАСТЬ ЖЕТІСУ']


# 1. Считаем сумму по годам
df_sum = (
    df[df['Регион'].isin(regions_needed)]
    .groupby('Год', as_index=False)['Nom_Income']
    .sum()
)

# 2. Добавляем название нового "региона"
df_sum['Регион'] = 'АЛМАТИНСКАЯ ОБЛАСТЬ С УЧЕТОМ ЖЕТЫСУ'

# 3. Приводим к тому же порядку колонок
df_sum = df_sum[['Регион', 'Год', 'Nom_Income']]

# 4. Добавляем обратно в исходный df_long
df = pd.concat([df, df_sum], ignore_index=True)

In [16]:
regions_needed_1= ['КАРАГАНДИНСКАЯ ОБЛАСТЬ', 'ОБЛАСТЬ ҰЛЫТАУ']


# 1. Считаем сумму по годам
df_sum = (
    df[df['Регион'].isin(regions_needed_1)]
    .groupby('Год', as_index=False)['Nom_Income']
    .sum()
)

# 2. Добавляем название нового "региона"
df_sum['Регион'] = 'КАРАГАНДИНСКАЯ ОБЛАСТЬ С УЧЕТОМ УЛЫТАУ'

# 3. Приводим к тому же порядку колонок
df_sum = df_sum[['Регион', 'Год', 'Nom_Income']]

# 4. Добавляем обратно в исходный df_long
df = pd.concat([df, df_sum], ignore_index=True)

In [17]:
regions_needed_2= ['ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ', 'ОБЛАСТЬ АБАЙ']


# 1. Считаем сумму по годам
df_sum = (
    df[df['Регион'].isin(regions_needed_2)]
    .groupby('Год', as_index=False)['Nom_Income']
    .sum()
)

# 2. Добавляем название нового "региона"
df_sum['Регион'] = 'ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ С УЧЕТОМ АБАЙ'

# 3. Приводим к тому же порядку колонок
df_sum = df_sum[['Регион', 'Год', 'Nom_Income']]

# 4. Добавляем обратно в исходный df_long
df = pd.concat([df, df_sum], ignore_index=True)

In [18]:
regions_needed_3 = ['ЮЖНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ', 'ТУРКЕСТАНСКАЯ ОБЛАСТЬ','Г.ШЫМКЕНТ']


# 1. Считаем сумму по годам
df_sum = (
    df[df['Регион'].isin(regions_needed_3)]
    .groupby('Год', as_index=False)['Nom_Income']
    .sum()
)

# 2. Добавляем название нового "региона"
df_sum['Регион'] = 'ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)'

# 3. Приводим к тому же порядку колонок
df_sum = df_sum[['Регион', 'Год', 'Nom_Income']]

# 4. Добавляем обратно в исходный df_long
df = pd.concat([df, df_sum], ignore_index=True)

In [19]:
to_drop = ['КАРАГАНДИНСКАЯ ОБЛАСТЬ', 'ОБЛАСТЬ ҰЛЫТАУ','ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ', 'ОБЛАСТЬ АБАЙ','АЛМАТИНСКАЯ ОБЛАСТЬ', 'ОБЛАСТЬ ЖЕТІСУ','ЮЖНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ', 'ТУРКЕСТАНСКАЯ ОБЛАСТЬ', 'Г.ШЫМКЕНТ']

df = df[~df['Регион'].isin(to_drop)]

In [20]:
df = df.reset_index(drop=True)
df.head(3)

                 Регион   Год  Nom_Income
0  РЕСПУБЛИКА КАЗАХСТАН  2000      6352.0
1   АКМОЛИНСКАЯ ОБЛАСТЬ  2000      4817.0
2   АКТЮБИНСКАЯ ОБЛАСТЬ  2000      6916.0

2-ой файл

In [21]:
cpa_1 = pd.read_excel(
    r'C:\Users\ktzhadmin\Desktop\Capstone project\Capstone_project_Data\CPA 2000-2010.xlsx',
    skiprows=1
)

cpa_1 = cpa_1.drop(columns=['Unnamed: 0'])
cpa_1= cpa_1.rename(columns={'Unnamed: 1': 'Год'})
cpa_1

     Год    CPA
0   2000  112.8
1   2001  108.8
2   2002  107.1
3   2003  107.1
4   2004  107.4
5   2005  108.1
6   2006  107.3
7   2007  126.6
8   2008  110.8
9   2009  103.0
10  2010  110.1

3-ий файл

In [22]:
cpa_2 = pd.read_excel(
    r'C:\Users\ktzhadmin\Desktop\Capstone project\Capstone_project_Data\CPA 2011 - 2024.xls',
    skiprows=10
)

cpa_2.columns = cpa_2.columns.str.extract(r'(\d{4})')[0]
cpa_1= cpa_1.rename(columns={'Unnamed: 1': 'Год'})
cpa_2 = cpa_2.rename(columns = {np.nan: 'Регион'})
cpa_2.head(3)

,Регион,2011,2011,2011,2011,2012,2012,2012,2012,2013,...,2023,2023,2024,2024,2024,2024,2025,2025,2025,2025
0,РЕСПУБЛИКА КАЗАХСТАН,"103,6","101,8","101,1","101,0","101,1","101,6","101,1","101,9","102,1",...,"101,7","102,2","102,6","101,7","101,6","102,3","103,5","103,5","102,6","102,4"
1,ОБЛАСТЬ АБАЙ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"101,4","102,0","103,0","101,5","101,6","102,8","103,1","103,2","102,5","102,6"
2,АКМОЛИНСКАЯ ОБЛАСТЬ,"103,4","101,3","101,7","100,7","101,1","101,5","100,8","101,6","102,5",...,"102,3","102,4","101,9","102,1","101,9","102,6","103,7","103,2","102,8","103,2"

In [23]:
cpa_2.fillna('0').head(3)

,Регион,2011,2011,2011,2011,2012,2012,2012,2012,2013,...,2023,2023,2024,2024,2024,2024,2025,2025,2025,2025
0,РЕСПУБЛИКА КАЗАХСТАН,"103,6","101,8","101,1","101,0","101,1","101,6","101,1","101,9","102,1",...,"101,7","102,2","102,6","101,7","101,6","102,3","103,5","103,5","102,6","102,4"
1,ОБЛАСТЬ АБАЙ,0,0,0,0,0,0,0,0,0,...,"101,4","102,0","103,0","101,5","101,6","102,8","103,1","103,2","102,5","102,6"
2,АКМОЛИНСКАЯ ОБЛАСТЬ,"103,4","101,3","101,7","100,7","101,1","101,5","100,8","101,6","102,5",...,"102,3","102,4","101,9","102,1","101,9","102,6","103,7","103,2","102,8","103,2"

In [24]:
# все кроме первой колонки (Регион)
cpa_2.iloc[:, 1:] = (
    cpa_2.iloc[:, 1:]
    .apply(lambda col: col.astype(str)
                        .str.replace('\xa0', '')
                        .str.replace('    ', '')
                        .str.replace(',', '.'))
)

# перевод в числа
cpa_2.iloc[:, 1:] = cpa_2.iloc[:, 1:].apply(pd.to_numeric, errors='coerce')

In [25]:
cpa_2['Регион'] = cpa_2['Регион'].astype(str).str.replace('    ', '')

In [26]:
# 1. Составим список колонок годов (числа)
years = [col for col in cpa_2.columns if col != 'Регион']

# 2. Melt: превращаем таблицу "широкую" в "длинную"
cpa_2 = cpa_2.melt(id_vars=['Регион'], value_vars=years,
                  var_name='Год', value_name='CPA')

# 3. Приведем 'Год' к int (на всякий случай)
cpa_2['Год'] = cpa_2['Год'].astype(int)

cpa_2.head(3)

                 Регион   Год    CPA
0  РЕСПУБЛИКА КАЗАХСТАН  2011  103.6
1          ОБЛАСТЬ АБАЙ  2011    NaN
2   АКМОЛИНСКАЯ ОБЛАСТЬ  2011  103.4

In [27]:

# 1. Считаем среднее по годам по индексам
cpa_2_mean = (
    cpa_2[cpa_2['Регион'].isin(regions_needed)]
    .groupby('Год', as_index=False)['CPA']
    .mean()
)

# 2. Добавляем название нового "региона"
cpa_2_mean['Регион'] = 'АЛМАТИНСКАЯ ОБЛАСТЬ С УЧЕТОМ ЖЕТЫСУ'

# 3. Приводим к тому же порядку колонок
cpa_2_mean = cpa_2_mean[['Регион', 'Год', 'CPA']]

# 4. Добавляем обратно в исходный df_long
cpa_2 = pd.concat([cpa_2, cpa_2_mean], ignore_index=True)
cpa_2

# 1. Считаем среднее по годам по индексам
cpa_2_mean = (
    cpa_2[cpa_2['Регион'].isin(regions_needed_1)]
    .groupby('Год', as_index=False)['CPA']
    .mean()
)

# 2. Добавляем название нового "региона"
cpa_2_mean['Регион'] = 'КАРАГАНДИНСКАЯ ОБЛАСТЬ С УЧЕТОМ УЛЫТАУ'

# 3. Приводим к тому же порядку колонок
cpa_2_mean = cpa_2_mean[['Регион', 'Год', 'CPA']]

# 4. Добавляем обратно в исходный df_long
cpa_2 = pd.concat([cpa_2, cpa_2_mean], ignore_index=True)





# 1. Считаем среднее по годам по индексам
cpa_2_mean = (
    cpa_2[cpa_2['Регион'].isin(regions_needed_2)]
    .groupby('Год', as_index=False)['CPA']
    .mean()
)

# 2. Добавляем название нового "региона"
cpa_2_mean['Регион'] = 'ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ С УЧЕТОМ АБАЙ'

# 3. Приводим к тому же порядку колонок
cpa_2_mean = cpa_2_mean[['Регион', 'Год', 'CPA']]

# 4. Добавляем обратно в исходный df_long
cpa_2 = pd.concat([cpa_2, cpa_2_mean], ignore_index=True)

# 1. Считаем среднее по годам по индексам
cpa_2_mean = (
    cpa_2[cpa_2['Регион'].isin(regions_needed_3)]
    .groupby('Год', as_index=False)['CPA']
    .mean()
)

# 2. Добавляем название нового "региона"
cpa_2_mean['Регион'] = 'ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)'

# 3. Приводим к тому же порядку колонок
cpa_2_mean = cpa_2_mean[['Регион', 'Год', 'CPA']]

# 4. Добавляем обратно в исходный df_long
cpa_2 = pd.concat([cpa_2, cpa_2_mean], ignore_index=True)



cpa_2 = cpa_2[~cpa_2['Регион'].isin(to_drop)]
cpa_2.head(3)

                 Регион   Год    CPA
0  РЕСПУБЛИКА КАЗАХСТАН  2011  103.6
2   АКМОЛИНСКАЯ ОБЛАСТЬ  2011  103.4
3   АКТЮБИНСКАЯ ОБЛАСТЬ  2011  103.4

In [28]:
regions = cpa_2[['Регион']].drop_duplicates()

In [29]:
regions = cpa_2[['Регион']].drop_duplicates()
# crossjoin - делаю размножение
cpa_1 = cpa_1.merge(regions, how='cross')
#привожу к такому же виде таблицу к cpa_2
cpa_1 = cpa_1[['Регион', 'Год', 'CPA']]
#обьеденяю
cpa_all = pd.concat([cpa_1, cpa_2], ignore_index=True)
#сортирую
cpa_all = cpa_all.sort_values(['Регион', 'Год']).reset_index(drop=True)
cpa_all.head(5)

                Регион   Год    CPA
0  АКМОЛИНСКАЯ ОБЛАСТЬ  2000  112.8
1  АКМОЛИНСКАЯ ОБЛАСТЬ  2001  108.8
2  АКМОЛИНСКАЯ ОБЛАСТЬ  2002  107.1
3  АКМОЛИНСКАЯ ОБЛАСТЬ  2003  107.1
4  АКМОЛИНСКАЯ ОБЛАСТЬ  2004  107.4

4-ый файл

In [30]:
mn_in = pd.read_excel(
    r'C:\Users\ktzhadmin\Desktop\Capstone project\Capstone_project_Data\Money income.xls',
    skiprows=10
)

mn_in.head(5)

,Регион,2006 год,2007 год,2008 год,2009 год,2010 год,2011 год,2012 год,2013 год,2014 год,2015 год,2016 год,2017 год,2018 год,2019 год,2020 год,2021 год,2022 год,2023 год,2024 год
0,РЕСПУБЛИКА КАЗАХСТАН,163 620,204 411,245 618,270 873,330 123,350 117,394 464,432 573,467 763,493 264,533 561,570 743,629 033,692 703,744 424,829 333,964 447,1 161 847,1 328 907
1,АКМОЛИНСКАЯ ОБЛАСТЬ,150 865,187 450,222 939,245 455,325 307,319 501,357 554,384 917,429 154,441 095,483 980,526 615,591 509,656 356,757 344,863 424,1 014 824,1 206 494,1 342 530
2,АКТЮБИНСКАЯ ОБЛАСТЬ,161 445,189 587,231 131,261 297,352 386,338 085,387 294,423 221,473 079,509 371,544 021,577 929,611 801,710 950,732 068,807 659,966 187,1 128 597,1 252 573
3,АЛМАТИНСКАЯ ОБЛАСТЬ,130 709,168 693,205 246,209 023,285 926,342 765,382 678,410 210,435 563,436 333,491 702,497 879,539 842,602 157,667 305,705 633,808 342,980 356,1 115 075
4,АТЫРАУСКАЯ ОБЛАСТЬ,182 696,253 381,288 461,301 550,413 737,338 774,366 726,392 254,407 778,419 192,461 758,505 690,566 212,618 888,696 406,730 117,872 771,961 179,1 127 295

In [31]:
#Составим список колонок годов (числа)
new_cols = []

for col in mn_in.columns:       #убрали слово год из наименований столбцов
    if 'год' in col:
        new_cols.append(int(''.join(filter(str.isdigit, col))))
    else:
        new_cols.append(col)

mn_in.columns = new_cols


years = [col for col in mn_in.columns if col != 'Регион']

# 2. Melt: превращаем таблицу "широкую" в "длинную"
mn_in = mn_in.melt(id_vars=['Регион'], value_vars=years,
                  var_name='Год', value_name='Money_Income')

# 3. Приведем 'Год' к int (на всякий случай)
mn_in['Год'] = mn_in['Год'].astype(int)

print(mn_in.head())

                    Регион   Год Money_Income
0     РЕСПУБЛИКА КАЗАХСТАН  2006      163 620
1      АКМОЛИНСКАЯ ОБЛАСТЬ  2006      150 865
2      АКТЮБИНСКАЯ ОБЛАСТЬ  2006      161 445
3      АЛМАТИНСКАЯ ОБЛАСТЬ  2006      130 709
4       АТЫРАУСКАЯ ОБЛАСТЬ  2006      182 696

In [32]:
mn_in['Регион'] = mn_in['Регион'].astype(str).str.replace('    ', '')

In [33]:
mn_in['Money_Income'] = mn_in['Money_Income'].astype(str).str.replace(' ', '')
mn_in['Money_Income'] = mn_in['Money_Income'].astype(float)

5-ый файл

In [35]:
mn_ex = pd.read_excel(
    r'C:\Users\ktzhadmin\Desktop\Capstone project\Capstone_project_Data\Money expenses.xls',
    skiprows=10
)

In [36]:
new_cols = []

for col in mn_ex.columns:       #убрали слово год из наименований столбцов
    if 'год' in col:
        new_cols.append(int(''.join(filter(str.isdigit, col))))
    else:
        new_cols.append(col)

mn_ex.columns = new_cols

In [37]:
#Составим список колонок годов (числа)

years = [col for col in mn_ex.columns if col != 'Регион']

# 2. Melt: превращаем таблицу "широкую" в "длинную"
mn_ex = mn_ex.melt(id_vars=['Регион'], value_vars=years,
                  var_name='Год', value_name='Money_Expenses')

# 3. Приведем 'Год' к int (на всякий случай)
mn_ex['Год'] = mn_ex['Год'].astype(int)

print(mn_ex.head())

                    Регион   Год Money_Expenses
0     РЕСПУБЛИКА КАЗАХСТАН  2011        346 706
1      АКМОЛИНСКАЯ ОБЛАСТЬ  2011        333 849
2      АКТЮБИНСКАЯ ОБЛАСТЬ  2011        360 590
3      АЛМАТИНСКАЯ ОБЛАСТЬ  2011        409 643
4       АТЫРАУСКАЯ ОБЛАСТЬ  2011        341 844

In [38]:
mn_ex['Регион'] = mn_in['Регион'].astype(str).str.replace('    ', '')

In [39]:
mn_ex['Money_Expenses'] = mn_ex['Money_Expenses'].astype(str).str.replace(' ', '')
mn_ex['Money_Expenses'] = mn_ex['Money_Expenses'].astype(float)

In [40]:
#обьединяем расходы и доходы

common_years = set(mn_in['Год']).intersection(mn_ex['Год'])

mn_in_filtered = mn_in[mn_in['Год'].isin(common_years)]
mn_ex_filtered = mn_ex[mn_ex['Год'].isin(common_years)]

mn = mn_in_filtered.merge(mn_ex_filtered, on=['Регион', 'Год'])

mn

                    Регион   Год  Money_Income  Money_Expenses
0     РЕСПУБЛИКА КАЗАХСТАН  2011      350117.0        346706.0
1      АКМОЛИНСКАЯ ОБЛАСТЬ  2011      319501.0        333849.0
2      АКТЮБИНСКАЯ ОБЛАСТЬ  2011      338085.0        360590.0
3      АЛМАТИНСКАЯ ОБЛАСТЬ  2011      342765.0        409643.0
4       АТЫРАУСКАЯ ОБЛАСТЬ  2011      338774.0        341844.0
..                     ...   ...           ...             ...
303              Г.ШЫМКЕНТ  2024      959893.0        890277.0
304  ТУРКЕСТАНСКАЯ ОБЛАСТЬ  2024      883231.0        767022.0
305         ОБЛАСТЬ ЖЕТІСУ  2024     1023757.0       1198030.0
306         ОБЛАСТЬ ҰЛЫТАУ  2024     1575813.0       1365545.0
307           ОБЛАСТЬ АБАЙ  2024     1208889.0        984289.0

[308 rows x 4 columns]

6-ой файл

In [41]:
con = pd.read_excel(
    r'C:\Users\ktzhadmin\Desktop\Capstone project\Capstone_project_Data\Consumption.xls',
    skiprows=10
)
con.head(5)

,Регион,2011 год,2012 год,2013 год,2014 год,2015 год,2016 год,2017 год,2018 год,2019 год,2020 год,2021 год,2022 год,2023 год,2024 год
0,РЕСПУБЛИКА КАЗАХСТАН,323 298,355 556,386 836,411 133,426 825,465 830,514 693,571 607,621 740,665 272,752 530,861 942,988 453,1 070 506
1,АКМОЛИНСКАЯ ОБЛАСТЬ,297 836,325 894,336 116,374 677,376 759,416 250,472 748,546 881,590 239,663 468,720 362,836 336,975 953,1 088 500
2,АКТЮБИНСКАЯ ОБЛАСТЬ,334 722,363 751,389 105,409 043,399 991,424 615,439 256,481 108,543 270,584 486,651 215,784 125,859 406,869 312
3,АЛМАТИНСКАЯ ОБЛАСТЬ,386 315,392 668,445 735,452 938,461 292,516 912,539 838,588 225,656 184,702 346,755 989,876 066,914 527,952 700
4,АТЫРАУСКАЯ ОБЛАСТЬ,312 882,339 947,352 116,361 812,376 582,424 538,461 712,504 153,531 871,572 820,613 921,728 943,797 613,847 314

In [42]:
#Составим список колонок годов (числа)
new_cols = []

for col in con.columns:       #убрали слово год из наименований столбцов
    if 'год' in col:
        new_cols.append(int(''.join(filter(str.isdigit, col))))
    else:
        new_cols.append(col)

con.columns = new_cols


years = [col for col in con.columns if col != 'Регион']

# 2. Melt: превращаем таблицу "широкую" в "длинную"
con = con.melt(id_vars=['Регион'], value_vars=years,
                  var_name='Год', value_name='Cons_expenses')

# 3. Приведем 'Год' к int (на всякий случай)
con['Год'] = con['Год'].astype(int)

print(con.head())

                    Регион   Год Cons_expenses
0     РЕСПУБЛИКА КАЗАХСТАН  2011       323 298
1      АКМОЛИНСКАЯ ОБЛАСТЬ  2011       297 836
2      АКТЮБИНСКАЯ ОБЛАСТЬ  2011       334 722
3      АЛМАТИНСКАЯ ОБЛАСТЬ  2011       386 315
4       АТЫРАУСКАЯ ОБЛАСТЬ  2011       312 882

In [43]:
con['Регион'] = con['Регион'].astype(str).str.replace('    ', '')
con['Cons_expenses'] = con['Cons_expenses'].astype(str).str.replace(' ', '')
con['Cons_expenses'] = con['Cons_expenses'].astype(float)

In [44]:
#Обьединяю mn и con чтобы легче было очистить данные
df_2 = mn.merge(con, on = ['Регион', 'Год'],how = 'left')

In [45]:
# считаем сумму
df_2_sum = (
    df_2[df_2['Регион'].isin(regions_needed)]
    .groupby('Год', as_index=False)[['Money_Income', 'Money_Expenses', 'Cons_expenses']]
    .sum()
)

# добавляем регион
df_2_sum['Регион'] = 'АЛМАТИНСКАЯ ОБЛАСТЬ С УЧЕТОМ ЖЕТЫСУ'

# порядок колонок
df_2_sum = df_2_sum[['Регион', 'Год', 'Money_Income', 'Money_Expenses', 'Cons_expenses']]

# добавляем обратно
df_2 = pd.concat([df_2, df_2_sum], ignore_index=True)

# считаем сумму
df_2_sum = (
    df_2[df_2['Регион'].isin(regions_needed_1)]
    .groupby('Год', as_index=False)[['Money_Income', 'Money_Expenses', 'Cons_expenses']]
    .sum()
)

# добавляем регион
df_2_sum['Регион'] = 'КАРАГАНДИНСКАЯ ОБЛАСТЬ С УЧЕТОМ УЛЫТАУ'

# порядок колонок
df_2_sum = df_2_sum[['Регион', 'Год', 'Money_Income', 'Money_Expenses', 'Cons_expenses']]

# добавляем обратно
df_2 = pd.concat([df_2, df_2_sum], ignore_index=True)

# считаем сумму
df_2_sum = (
    df_2[df_2['Регион'].isin(regions_needed_2)]
    .groupby('Год', as_index=False)[['Money_Income', 'Money_Expenses', 'Cons_expenses']]
    .sum()
)

# добавляем регион
df_2_sum['Регион'] = 'ВОСТОЧНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ С УЧЕТОМ АБАЙ'

# порядок колонок
df_2_sum = df_2_sum[['Регион', 'Год', 'Money_Income', 'Money_Expenses', 'Cons_expenses']]

# добавляем обратно
df_2 = pd.concat([df_2, df_2_sum], ignore_index=True)

# считаем сумму
df_2_sum = (
    df_2[df_2['Регион'].isin(regions_needed_3)]
    .groupby('Год', as_index=False)[['Money_Income', 'Money_Expenses', 'Cons_expenses']]
    .sum()
)

# добавляем регион
df_2_sum['Регион'] = 'ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)'

# порядок колонок
df_2_sum = df_2_sum[['Регион', 'Год', 'Money_Income', 'Money_Expenses', 'Cons_expenses']]

# добавляем обратно
df_2 = pd.concat([df_2, df_2_sum], ignore_index=True)

df_2 = df_2[~df_2['Регион'].isin(to_drop)]

In [46]:
df_2.isna().sum()

Регион            0
Год               0
Money_Income      0
Money_Expenses    0
Cons_expenses     0
dtype: int64

7-ой файл

In [47]:
msl = pd.read_excel(
    r'C:\Users\ktzhadmin\Desktop\Capstone project\Capstone_project_Data\MSL.xlsx')

#Итоговое объединение данных

In [48]:
df = df.merge(cpa_all, on=['Регион', 'Год'], how='left')
df

                                    Регион   Год  Nom_Income       CPA
0                     РЕСПУБЛИКА КАЗАХСТАН  2000      6352.0     112.8
1                      АКМОЛИНСКАЯ ОБЛАСТЬ  2000      4817.0     112.8
2                      АКТЮБИНСКАЯ ОБЛАСТЬ  2000      6916.0     112.8
3                       АТЫРАУСКАЯ ОБЛАСТЬ  2000     15056.0     112.8
4            ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ  2000      6555.0     112.8
..                                     ...   ...         ...       ...
966  ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)  2020    139168.0  101.8125
967  ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)  2021    150817.0     102.1
968  ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)  2022    192874.0     104.5
969  ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)  2023    223953.0    102.45
970  ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)  2024    260664.0   101.825

[971 rows x 4 columns]

In [49]:
#у ЮКО нет данных CPA c 2000 по 2018 гг, поэтому хочу заполнить средним значением CPA по годам

#1. Посчитаем среднее по каждому году
df['CPA_mean_year'] = df.groupby('Год')['CPA'].transform('mean')
#2. заполняю пропуски
df['CPA'] = df['CPA'].fillna(df['CPA_mean_year'])
#3. удаляю столбец
df['CPA'] = df['CPA'].fillna(df['CPA_mean_year'])
drop_columns = ['CPA_mean_year']
df = df.drop(columns = drop_columns)

In [50]:
df['Real_Income'] = df['Nom_Income'] / (df['CPA'] / 100)

In [51]:
df_1 = df.sort_values(['Регион', 'Год'])
df_2_subset = df_2[['Регион', 'Год', 'Cons_expenses']]
df_1 = pd.merge(df_1, df_2_subset, on=['Регион', 'Год'], how='left', suffixes=('', '_new'))
df_1.fillna(0, inplace=True)

In [52]:
df_2 = df_2.merge(msl, on = ['Год'],how = 'left')

#Расчет показателей

In [53]:
#Динамика доходов

df_1['nominal_growth_%'] = df_1.groupby('Регион')['Nom_Income'].pct_change() * 100
df_1['real_growth_%'] = df_1.groupby('Регион')['Real_Income'].pct_change() * 100

#Сравнение номинальных и реальных насколько инфляция сьедает доходы то же для декомпозиции доходов
df_1['inflation_contribution_%'] = -((df_1['nominal_growth_%'] - df_1['real_growth_%'])).astype(float)

#чтобы показать декомпозицию роста дохода
df_1['nominal_contribution_%'] = df_1['nominal_growth_%']


#Какую долю роста сьела инфляция
df_1['inflation_share_%'] = (
    df_1['inflation_contribution_%'] / df_1['nominal_contribution_%']
) * 100

#Эластичность дохода к инфляции
df_1['elasticity'] = df_1['real_growth_%'] / df_1['CPA']

df_1.fillna(0, inplace=True)

#Доля потребления в доходах
df_1['consumption_share_real'] = df_1['Cons_expenses'] / df_1['Real_Income'] * 100

df_1

,Регион,Год,Nom_Income,CPA,Real_Income,Cons_expenses,nominal_growth_%,real_growth_%,inflation_contribution_%,nominal_contribution_%,inflation_share_%,elasticity,consumption_share_real
0,АКМОЛИНСКАЯ ОБЛАСТЬ,2000,4817.0,112.8000,4270.390071,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000
1,АКМОЛИНСКАЯ ОБЛАСТЬ,2001,5656.0,108.8000,5198.529412,0.0,17.417480,21.734299,4.316819e+00,17.417480,2.478441e+01,0.199764,0.000000
2,АКМОЛИНСКАЯ ОБЛАСТЬ,2002,6765.0,107.1000,6316.526611,0.0,19.607496,21.506028,1.898532e+00,19.607496,9.682683e+00,0.200803,0.000000
3,АКМОЛИНСКАЯ ОБЛАСТЬ,2003,7976.0,107.1000,7447.245565,0.0,17.900961,17.900961,2.486900e-14,17.900961,1.389255e-13,0.167142,0.000000
4,АКМОЛИНСКАЯ ОБЛАСТЬ,2004,9441.0,107.4000,8790.502793,0.0,18.367603,18.036967,-3.306358e-01,18.367603,-1.800103e+00,0.167942,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
966,"ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)",2020,139168.0,101.8125,136690.484960,979697.0,13.281021,12.766423,-5.145976e-01,13.281021,-3.874684e+00,0.125392,716.726552
967,"ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)",2021,150817.0,102.1000,147714.985309,1096434.0,8.370459,8.065302,-3.051568e-01,8.370459,-3.645640e+00,0.078994,742.263216
968,"ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)",2022,192874.0,104.5000,184568.421053,1328757.0,27.886114,24.949016,-2.937097e+00,27.886114,-1.053247e+01,0.238747,719.926514
969,"ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)",2023,223953.0,102.4500,218597.364568,1522509.0,16.113629,18.437035,2.323406e+00,16.113629,1.441889e+01,0.179961,696.490099
970,"ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)",2024,260664.0,101.8250,255992.143383,1590383.0,16.392279,17.106692,7.144137e-01,16.392279,4.358233e+00,0.168001,621.262426

In [54]:
#для понимания влияния кризисных ситуаций
# Список базовых годов
base_years = [2008, 2015, 2020]

for year in base_years:
    base_dict = (
        df_1[df_1['Год'] == year]
        .set_index('Регион')['Real_Income']
        .to_dict()
    )

    df_1[f'income_index_{year}'] = df_1['Real_Income'] / df_1['Регион'].map(base_dict) * 100

df_1

,Регион,Год,Nom_Income,CPA,Real_Income,Cons_expenses,nominal_growth_%,real_growth_%,inflation_contribution_%,nominal_contribution_%,inflation_share_%,elasticity,consumption_share_real,income_index_2008,income_index_2015,income_index_2020
0,АКМОЛИНСКАЯ ОБЛАСТЬ,2000,4817.0,112.8000,4270.390071,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,17.996319,8.242044,4.058352
1,АКМОЛИНСКАЯ ОБЛАСТЬ,2001,5656.0,108.8000,5198.529412,0.0,17.417480,21.734299,4.316819e+00,17.417480,2.478441e+01,0.199764,0.000000,21.907693,10.033394,4.940407
2,АКМОЛИНСКАЯ ОБЛАСТЬ,2002,6765.0,107.1000,6316.526611,0.0,19.607496,21.506028,1.898532e+00,19.607496,9.682683e+00,0.200803,0.000000,26.619167,12.191179,6.002892
3,АКМОЛИНСКАЯ ОБЛАСТЬ,2003,7976.0,107.1000,7447.245565,0.0,17.900961,17.900961,2.486900e-14,17.900961,1.389255e-13,0.167142,0.000000,31.384254,14.373517,7.077467
4,АКМОЛИНСКАЯ ОБЛАСТЬ,2004,9441.0,107.4000,8790.502793,0.0,18.367603,18.036967,-3.306358e-01,18.367603,-1.800103e+00,0.167942,0.000000,37.045022,16.966063,8.354027
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
966,"ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)",2020,139168.0,101.8125,136690.484960,979697.0,13.281021,12.766423,-5.145976e-01,13.281021,-3.874684e+00,0.125392,716.726552,745.339849,392.083857,100.000000
967,"ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)",2021,150817.0,102.1000,147714.985309,1096434.0,8.370459,8.065302,-3.051568e-01,8.370459,-3.645640e+00,0.078994,742.263216,805.453758,423.706604,108.065302
968,"ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)",2022,192874.0,104.5000,184568.421053,1328757.0,27.886114,24.949016,-2.937097e+00,27.886114,-1.053247e+01,0.238747,719.926514,1006.406548,529.417233,135.026532
969,"ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)",2023,223953.0,102.4500,218597.364568,1522509.0,16.113629,18.437035,2.323406e+00,16.113629,1.441889e+01,0.179961,696.490099,1191.958071,627.026072,159.921420
970,"ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)",2024,260664.0,101.8250,255992.143383,1590383.0,16.392279,17.106692,7.144137e-01,16.392279,4.358233e+00,0.168001,621.262426,1395.862672,734.289493,187.278685

In [55]:
#Баланс: тратят больше или меньше, чем зарабатывают
df_2['balance'] = df_2['Money_Income'] - df_2['Money_Expenses']

#Норма сбережений
df_2['saving_rate'] = (df_2['Money_Income'] - df_2['Money_Expenses']) / df_2['Money_Income'] * 100

#Структура расходов
df_2['consumption_share_total'] = df_2['Cons_expenses'] / df_2['Money_Expenses'] * 100

df_2

,Регион,Год,Money_Income,Money_Expenses,Cons_expenses,MSL,balance,saving_rate,consumption_share_total
0,РЕСПУБЛИКА КАЗАХСТАН,2011,350117.0,346706.0,323298.0,15999.0,3411.0,0.974246,93.248458
1,АКМОЛИНСКАЯ ОБЛАСТЬ,2011,319501.0,333849.0,297836.0,15999.0,-14348.0,-4.490753,89.212788
2,АКТЮБИНСКАЯ ОБЛАСТЬ,2011,338085.0,360590.0,334722.0,15999.0,-22505.0,-6.656610,92.826202
3,АТЫРАУСКАЯ ОБЛАСТЬ,2011,338774.0,341844.0,312882.0,15999.0,-3070.0,-0.906209,91.527714
4,ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ,2011,315947.0,288603.0,273012.0,15999.0,27344.0,8.654616,94.597769
...,...,...,...,...,...,...,...,...,...
233,"ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)",2020,1037962.0,1010008.0,979697.0,31925.5,27954.0,2.693162,96.998935
234,"ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)",2021,1144194.0,1128576.0,1096434.0,34302.0,15618.0,1.364978,97.151986
235,"ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)",2022,1302786.0,1370690.0,1328757.0,36703.5,-67904.0,-5.212214,96.940738
236,"ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)",2023,1684802.0,1576534.0,1522509.0,40567.0,108268.0,6.426156,96.573179
237,"ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)",2024,1843124.0,1657299.0,1590383.0,43407.0,185825.0,10.082067,95.962346

In [56]:
df_2

,Регион,Год,Money_Income,Money_Expenses,Cons_expenses,MSL,balance,saving_rate,consumption_share_total
0,РЕСПУБЛИКА КАЗАХСТАН,2011,350117.0,346706.0,323298.0,15999.0,3411.0,0.974246,93.248458
1,АКМОЛИНСКАЯ ОБЛАСТЬ,2011,319501.0,333849.0,297836.0,15999.0,-14348.0,-4.490753,89.212788
2,АКТЮБИНСКАЯ ОБЛАСТЬ,2011,338085.0,360590.0,334722.0,15999.0,-22505.0,-6.656610,92.826202
3,АТЫРАУСКАЯ ОБЛАСТЬ,2011,338774.0,341844.0,312882.0,15999.0,-3070.0,-0.906209,91.527714
4,ЗАПАДНО-КАЗАХСТАНСКАЯ ОБЛАСТЬ,2011,315947.0,288603.0,273012.0,15999.0,27344.0,8.654616,94.597769
...,...,...,...,...,...,...,...,...,...
233,"ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)",2020,1037962.0,1010008.0,979697.0,31925.5,27954.0,2.693162,96.998935
234,"ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)",2021,1144194.0,1128576.0,1096434.0,34302.0,15618.0,1.364978,97.151986
235,"ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)",2022,1302786.0,1370690.0,1328757.0,36703.5,-67904.0,-5.212214,96.940738
236,"ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)",2023,1684802.0,1576534.0,1522509.0,40567.0,108268.0,6.426156,96.573179
237,"ТУРКЕСТАНСКАЯ ОБЛАСТЬ(ЮКО, Г.ШЫМКЕНТ)",2024,1843124.0,1657299.0,1590383.0,43407.0,185825.0,10.082067,95.962346

In [61]:
!pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in c:\users\ktzhadmin\anaconda3\lib\site-packages (2.9.11)

In [66]:
from sqlalchemy import create_engine

# Параметры подключения – измени под своё окружение
# здесь нужно аккуратно, потому что по-другому он не загрузит данные с python ->sql
DB_USER = 'postgres'
DB_PASS = 'ShDoss1976**'
DB_HOST = 'localhost'
DB_PORT = '5432'
DB_NAME = 'Capstone_project'

engine = create_engine(f'postgresql://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}')

df_1.to_sql('nominal_real_income', engine, if_exists='replace', index=False)
df_2.to_sql('money_income_expenses', engine, if_exists='replace', index=False)

print('Очищенные данные выгружены в PostgreSQL!')

Очищенные данные выгружены в PostgreSQL!